title: KIM
copyright: "2023, HTW Dresden Torsten Munkelt"
author: Oleg Bissing, Paul Christ, Torsten Munkelt

execute:
  execute_notebooks: "force"

html:
  use_edit_page_button: true
  use_repository_button: true
  use_issues_button: true
  baseurl: https://HTW-ALADIN.github.io/kim

repository:
  url: https://github.com/HTW-ALADIN/kim
  branch: source

launch_buttons:
  binderhub_url: "https://mybinder.org"
  colab_url: "https://colab.research.google.com"
  thebe: true

latex:
  latex_documents:
    targetname: KIM.tex

parse:
  myst_enable_extensions:
    - html_image
    - dollarmath
    - amsmath
    - colon_fence
    - dollarmath
    - linkify
    - substitution
    - tasklist

bibtex_bibfiles:
  - bibliography.bib

sphinx:
  config:
    bibtex_reference_style: author_year
    html_show_copyright: false
    latex_toplevel_sectioning: part
    latex_show_pagerefs: true
    latex_show_urls: "footnote"
